### ISSUE TITLE
Reliability of event publishing architecture

### ISSUE THREAD

**Issue by gedw99** [simpleiot/simpleiot#263]
Just wondering if the genji stores the events before pushing them to NATS ?

The nginx article ( https://www.nginx.com/blog/event-driven-data-management-microservices/#Achieving-Atomicity ) it says you need an event table if you want atomicity. 

If we don’t want to be left in an inconsistent state if seems the right way to go ?.  The events are then send to NATS. Assuming NATS can do ACK’s then you can reliably delete the event in the dB .

**Comment by cbrake** [comment]
good question -- the way SIOT works is all writes to DB go through NATS first. This is one reason all the function in https://github.com/simpleiot/simpleiot/blob/master/db/genji.go are private -- I want to force all db writes to go through NATS so anyway has easy visibility of data changes through NATS. Does this cover the consistency concern?

Eventually we may need to add write caching/buffering as well to improve performance. I'm not sure how databases handle this -- perhaps if the machine or db application crashes, there is no guarantee of consistency? I'm reading a pretty good [book](https://community.tmpdir.org/t/book-review-designing-data-intensive-applications/288/8) on all this right now -- should re-read the consistency section again.

This article is also interesting: https://discuss.dgraph.io/t/making-badger-crash-resilient-with-alice-dgraph-blog/1685

Genji supports both bolt and badger stores -- I've been using bolt because it is simpler and writes are much faster.

**Comment by gedw99** [comment]
Going through nats to the dB is fine. That’s atomic . We can assume NATS will guarantee it eventually hits the db.

I was more curious about events being created server side ( due to do logic or hooks )  and those events being propagated to nats and out to the clients. But it maybe it’s out of scope because the siot server just does not have this use case ?  

i don’t know enough yet about siot to answer this so if you know it would be useful and maybe we can close this issue.

**Comment by cbrake** [comment]
Here is some areas where that happens:

https://github.com/simpleiot/simpleiot/blob/master/db/nats-handler.go
https://github.com/simpleiot/simpleiot/blob/master/db/rules.go
https://github.com/simpleiot/simpleiot/blob/master/node/modbus.go#L161
https://github.com/simpleiot/simpleiot/blob/master/node/upstream.go

Most of this happens in the same application process on the server, edge, or wherever SIOT is running. The SendNodePoint can be called with Ack enabled or not (requires we hear back from server). I think the error rate of NATS on the same machine will be very low even with Acks. If the point is not communicated, then the cached node state will not reflect it and it will not be written to the DB. If a user changed the point, it will be obvious, and they can redo the operation. If it is sensor data, it will be communicated again. Rule states are a little more tricky and could cause problems. 

This is not well thought out yet, so welcome discussion.

**Comment by gedw99** [comment]
Hey @cbrake 

I went through the list plus docs and comments, but found it very hard to test the system.

I saw the Sim, flag which could help ? Is there a Test client i can boot up with data, that allows me to test data Points gong in and out of the system. I would boot up 3 test client, and then network partition them like a Chaos controller to see how to really handles things going on and offline.

**Comment by cbrake** [comment]
SIOT is the client :-)

The easiest scenario is to set up two instances as I did here:

https://www.youtube.com/watch?v=6xB-gXUynQc

With config options, you can have one instance run on different http/NATS ports than the other.

https://docs.simpleiot.org/go/configuration/

Here is how I set up a 2nd SIOT instance:

```
[cbrake@ceres go2]$ more local.sh 
. envsetup.sh

export SIOT_HTTP_PORT=8081
export SIOT_NATS_PORT=4223
export SIOT_NATS_HTTP_PORT=8223
export SIOT_NATS_SERVER=nats://localhost:4223
```
The Sim flag should probably be removed, as I don't think that is relevant any more, and likely broke.

One interesting thing you can do is run this to watch NATS traffic:

`./siot -logNats`

This gives you a very clear picture of what is going on. 

Docs need a lot of work -- I've been thinking of starting a separate user docs section, as pretty mech everything is from a developer perspective right now.

**Comment by cbrake** [comment]
Using variable nodes is a handy way to simulate values changing -- again, the video shows that.

**Comment by gedw99** [comment]
thanks @cbrake 

that helps so much !!

I made a makefile to replace the current bash built script so i have more control. If you want a PR of it let me know. Make is not for everyone i know. But it makes it build, test and do CI cross platform.

I can see now that the best way to test will be to talk to the API, and then orchestrate hitting the system and cross checking what comes back. A bit like the ``` ./siot -logNats ```. but with a golang testing structure above it.

I think that the way to test it will be to hold an Event sourcing Command on the Test harness side, and then replay the Commands into the system, via Test Command Handlers, and then check that its correct in the actual system. Maybe with 3 NATS, like in your demo. 

I am also curious where Types should be defined and then surfaced ?  If i want to add a Service ( like the twillo SMS video), then i have to write golang but also elm ? Or is the elm Reflective off the Node Point data structure at runtime ? 

I am also quite keen to build a bit more around Genji that is Siot specific. So that as a dev you can program on the upper layer, and also easily see the effects inside genji.  If you have any ideas there, it would be interesting.

Sorry this issue has become a bit of an Epic discussion... Hope thats ok..

**Comment by cbrake** [comment]
> I made a makefile to replace the current bash built script so i have more control. If you want a PR of it let me know. Make is not for everyone i know. But it makes it build, test and do CI cross platform.

A Makefile was already suggested: https://github.com/simpleiot/simpleiot/issues/46

If complex build logic is required, then a Makefile may make sense. To date, I've tried to keep the build system simple enough I did not need Make -- this has largely been possible because the Go/Elm build tools are so good and fast. As soon as we get Go:embed working, it will get even simpler (there is a PR out for it, but is currently stalled). 

Make is powerful, but I feel it is also fairly obscure and hard to read unless you are an expert in it (compared to simple shell functions) -- too much obscure syntax and magic and very unlike Go and Elm. However, this may just be personal preference. I'm willing to consider Make if we need it, but would like to understand what problems it solves first. Many people solve problems by layering complexity on top of complexity instead of fixing/simplifying the underlying problems. 

> 
> I can see now that the best way to test will be to talk to the API, and then orchestrate hitting the system and cross checking what comes back. A bit like the `./siot -logNats`. but with a golang testing structure above it.
> 
> I think that the way to test it will be to hold an Event sourcing Command on the Test harness side, and then replay the Commands into the system, via Test Command Handlers, and then check that its correct in the actual system. Maybe with 3 NATS, like in your demo.

I would like more end-to-end/functional testing -- I think that will be critical for an IoT systems as we add more features.

Especially with the catchup sync code -- I think there are still some minor issues with that the testing would help flush out.

> I am also quite keen to build a bit more around Genji that is Siot specific. So that as a dev you can program on the upper layer, and also easily see the effects inside genji. If you have any ideas there, it would be interesting.

I've not thought about this much yet. As time goes on, I'm tending to expose more and more through NATs and do less and less in Genji. I think testing could follow a similar trend. In general I think higher level testing is more maintainable, because with low level tests, you end up changing code in two places every time you change anything. Low level unit tests are definitely useful for algorithms, but can also add maint burden if not implemented carefully.

We currently read cache all the nodes for performance, and will probably eventually implement some type of write buffer/caching, so this is another reason it may be best to focus testing at the NATS api level.

The way this is working out is rather strange -- as time goes on I'm becoming less and less dependent on the database capabilities, which is very different than most applications, where everything centers around the database. Not sure if this is good enough -- again, I get the sense I'm [doing things really right or really wrong](https://twitter.com/simple_iot/status/1435671816530497542).

> Sorry this issue has become a bit of an Epic discussion... Hope thats ok..
