### ISSUE TITLE
add node type to edge table

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#460]

**Comment by cbrake** [comment]
@bminer I'm working on this now, and working through how to populate the edge type. In the past, we've sent a type point when the node points to determine the node type. I'm thinking it might make more sense to send that with the edge points. This will require reworking some of the client code. Thoughts?

**Comment by bminer** [comment]
I can see it both ways, and I would lean toward not changing it.

On one hand, it makes node creation easier because you only need the node edge and the node point is unneeded.

On the other hand, when nodes are duplicated throughout the graph, it might make more sense for the node type to be encoded with the node points, not the duplicated various edges.  For example, you want it to be impossible for multiple node edges to have conflicting node types.

What's your motivation for implementing this change?

**Comment by cbrake** [comment]
Primary motivation for changing is that it makes the getNodes operation more efficient when you specify the type when fetching a node. It also feels cleaner. There are a lot of operations where we are traversing node graphs (managers looking for new nodes, etc). And, I think these operations will increase in the future.

I've also simplified the API and removed the "none" option for fetching nodes as this is not necessary and generally was just confusing things. 

I'm 95% through implementing this -- it has been a lot of work but feels like the right approach.

https://github.com/simpleiot/simpleiot/pull/462

One challenge I've run into is the edge gets populated before the node points, so this sometimes triggers things like the client manager to act before the node is populated. This is one downside of not having "transactions" but is a reality in distributed systems where some data may get there and some may not, so the system needs to be designed to handle all these scenarios and eventually be consistent.

**Comment by cbrake** [comment]
I solved the timing issues by sending the node points first and then the edge/edge points. This seems right as the node becomes "alive" when you send its type, so you want all the data (node points) to exist first.

However, still debugging an issue with hash inconsistencies when running sync, so debugging that now.

**Comment by cbrake** [comment]
implemented.
